apiVersion: v1
kind: ReplicationController
metadata:
  name: overheid
  namespace: ebms-adapter-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: overheid
    spec:
      containers:
        - name: overheid
          image: eluinstra/ebms-adapter-overheid-pg
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 8443
            - name: ebms
              containerPort: 8888
            - name: jms
              containerPort: 61616
