apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ebms-adapter-demo
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: db
      port: 5432
      targetPort: 5432
