apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: overheid
  namespace: ebms-adapter-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overheid
  template:
    metadata:
      labels:
        app: overheid
    spec:
      containers:
        - name: overheid
          image: eluinstra/ebms-adapter-overheid
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 8080
            - name: ebms
              containerPort: 8888
