apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: overheid
  namespace: ebms-adapter-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overheid
  template:
    metadata:
      labels:
        app: overheid
    spec:
      containers:
        - name: overheid
          image: eluinstra/ebms-adapter-bin
          env:
            - name: JAVA_ARGS
              value: "-Dlog4j.configurationFile=log4j2.xml"
            - name: https_verifyHostnames
              value: "false"
            - name: ebms_jdbc_update
              value: "true"
          command: ["./start.sh"]
          args: ["-hsqldb","-soap"]
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 8080
            - name: ebms
              containerPort: 8888
