apiVersion: v1
kind: Service
metadata:
  name: overheid
spec:
  type: NodePort
  selector:
    app: overheid
  ports:
    - name: api
      port: 8080
      targetPort: api
    - name: ebms
      port: 8888
      targetPort: ebms
