apiVersion: v1
kind: Service
metadata:
  name: overheid
spec:
  type: NodePort
  # type: LoadBalancer
  selector:
    app: overheid
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      nodePort: 30000
    - name: ebms
      port: 8888
      targetPort: 8888
