apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: digipoort
spec:
  replicas: 1
  selector:
    matchLabels:
      app: digipoort
  template:
    metadata:
      labels:
        app: digipoort
    spec:
      containers:
        - name: digipoort
          image: eluinstra/ebms-adapter-digipoort
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 8080
            - name: ebms
              containerPort: 8888
