apiVersion: v1
kind: Service
metadata:
  name: digipoort
spec:
  type: NodePort
  selector:
    app: digipoort
  ports:
    - name: api
      port: 8080
      targetPort: api
    - name: ebms
      port: 8888
      targetPort: ebms
